# Generated by Django 5.1.3 on 2024-11-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_api', '0002_alter_feedbackmodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
